// <auto-generated />
namespace Management.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addApplyProcess4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addApplyProcess4));
        
        string IMigrationMetadata.Id
        {
            get { return "202212010929350_addApplyProcess4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
